// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Project_Planner_API.Data;

#nullable disable

namespace Project_Planner_API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251113150900_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Project_Planner_API.Data.Entities.ResultEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Results", (string)null);
                });

            modelBuilder.Entity("Project_Planner_API.Data.Entities.StudentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Students", (string)null);
                });

            modelBuilder.Entity("Project_Planner_API.Data.Entities.SubjectEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ResultId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ResultId");

                    b.HasIndex("TeamId");

                    b.ToTable("Subjects", (string)null);
                });

            modelBuilder.Entity("Project_Planner_API.Data.Entities.TaskEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ResponsibleTeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ResultEntityId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("ResponsibleTeamId");

                    b.HasIndex("ResultEntityId");

                    b.ToTable("Tasks", (string)null);
                });

            modelBuilder.Entity("Project_Planner_API.Data.Entities.TeamEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Teams", (string)null);
                });

            modelBuilder.Entity("StudentEntityTaskEntity", b =>
                {
                    b.Property<Guid>("ResponsibleStudentsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TasksId")
                        .HasColumnType("uuid");

                    b.HasKey("ResponsibleStudentsId", "TasksId");

                    b.HasIndex("TasksId");

                    b.ToTable("StudentEntityTaskEntity");
                });

            modelBuilder.Entity("StudentEntityTeamEntity", b =>
                {
                    b.Property<Guid>("StudentsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeamsId")
                        .HasColumnType("uuid");

                    b.HasKey("StudentsId", "TeamsId");

                    b.HasIndex("TeamsId");

                    b.ToTable("StudentEntityTeamEntity");
                });

            modelBuilder.Entity("Project_Planner_API.Data.Entities.SubjectEntity", b =>
                {
                    b.HasOne("Project_Planner_API.Data.Entities.ResultEntity", "Result")
                        .WithMany()
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project_Planner_API.Data.Entities.TeamEntity", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Result");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Project_Planner_API.Data.Entities.TaskEntity", b =>
                {
                    b.HasOne("Project_Planner_API.Data.Entities.TaskEntity", "Parent")
                        .WithMany("Tasks")
                        .HasForeignKey("ParentId");

                    b.HasOne("Project_Planner_API.Data.Entities.TeamEntity", "ResponsibleTeam")
                        .WithMany()
                        .HasForeignKey("ResponsibleTeamId");

                    b.HasOne("Project_Planner_API.Data.Entities.ResultEntity", null)
                        .WithMany("Tasks")
                        .HasForeignKey("ResultEntityId");

                    b.Navigation("Parent");

                    b.Navigation("ResponsibleTeam");
                });

            modelBuilder.Entity("StudentEntityTaskEntity", b =>
                {
                    b.HasOne("Project_Planner_API.Data.Entities.StudentEntity", null)
                        .WithMany()
                        .HasForeignKey("ResponsibleStudentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project_Planner_API.Data.Entities.TaskEntity", null)
                        .WithMany()
                        .HasForeignKey("TasksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StudentEntityTeamEntity", b =>
                {
                    b.HasOne("Project_Planner_API.Data.Entities.StudentEntity", null)
                        .WithMany()
                        .HasForeignKey("StudentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project_Planner_API.Data.Entities.TeamEntity", null)
                        .WithMany()
                        .HasForeignKey("TeamsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Project_Planner_API.Data.Entities.ResultEntity", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Project_Planner_API.Data.Entities.TaskEntity", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
